<a href="https://colab.research.google.com/github/Bharat-KR25/Data_sets/blob/main/assn_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
import pandas as pd
# ---- A1. Create a 1D NumPy array for Week 1 ----
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print("\nA1. Week 1 temperatures array:")
print(temperatures_w1)
# ---- A2. Inspection and Properties ----
print("\nA2. Inspection of temperatures_w1:")
print(f"  Shape       : {temperatures_w1.shape}")
print(f"  Data type   : {temperatures_w1.dtype}")
print(f"  No. elements: {temperatures_w1.size}")

# ---- A3. Array Operations ----
temperatures_w1_fahrenheit = (temperatures_w1 * 9 / 5) + 32
print("\nA3. Celsius to Fahrenheit conversion:")
print(f"  Fahrenheit: {temperatures_w1_fahrenheit}")
print(f"  Max temperature (C): {temperatures_w1.max()}")
print(f"  Min temperature (C): {temperatures_w1.min()}")
print(f"  Mean temperature (C): {temperatures_w1.mean():.1f}")
first_three_days  = temperatures_w1[0:3]
print (first_three_days )
weekend_days = temperatures_w1[-2:]
middle_three_days = temperatures_w1[2:5]
print("\nA4. Slicing and Indexing:")
print(f"  First three days       : {first_three_days}")
print(f"  Weekend (last 2 days)  : {weekend_days}")
print(f"  Middle three days      : {middle_three_days}")
# ---- A5. Create a 2D array (Week 1 and Week 2) ----
temperatures_w2 = np.array([19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1])
temperatures = np.array([temperatures_w1, temperatures_w2])
print("\nA5. 2D temperatures array (rows = weeks):")
print(temperatures)

# ---- A6. Inspect and Slice the 2D Array ----
print("\nA6. Inspection of 2D temperatures array:")
print(f"  Shape       : {temperatures.shape}")
print(f"  Data type   : {temperatures.dtype}")
print(f"  No. elements: {temperatures.size}")

week1_row = temperatures[0]
week2_row = temperatures[1]
week1_weekend = temperatures[0, -2:]
week2_weekend = temperatures[1, -2:]
both_weekends = temperatures[:, -2:]

print(f"\n  Week 1 temperatures       : {week1_row}")
print(f"  Week 2 temperatures       : {week2_row}")
print(f"  Week 1 weekend            : {week1_weekend}")
print(f"  Week 2 weekend            : {week2_weekend}")
print(f"  Both weeks' weekends:\n{both_weekends}")

# PART B: PANDAS SERIES
# ---- B1. Creating a Pandas Series ----
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)
print("\nB1. Marks Series:")
print(marks)

# ---- B2. Indexing and Slicing ----
first_rank_mark_iloc = marks.iloc[0]
top3_loc = marks.loc[['Rank1', 'Rank2', 'Rank3']]
third_rank_iloc = marks.iloc[2]
above_90 = marks[marks > 90]

print("\nB2. Indexing and Slicing:")
print(f"  1st rank mark (integer position): {first_rank_mark_iloc}")
print(f"  Top 3 ranks (.loc):\n{top3_loc}")
print(f"  3rd ranked student's mark (.iloc): {third_rank_iloc}")
print(f"  Ranks with marks > 90:\n{above_90}")

# ---- B3. Manipulating the Series ----
marks['Rank1'] = 100
print("\nB3a. After updating Rank1's mark to 100:")
print(marks)

marks = marks.drop('Rank5')
print("\nB3b. After removing the last rank (Rank5):")
print(marks)

cgpa = marks / 10
print("\nB3c. CGPA (marks / 10):")
print(cgpa)

# PART C: PANDAS DATAFRAME

# ---- C1. Creating a Pandas DataFrame ----
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
                         'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West',
               'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print("\nC1. Transactions DataFrame:")
print(transactions)

# ---- C2. Data Exploration ----
print("\nC2. Data Exploration:")

print("\n  Full DataFrame:")
print(transactions)

print("\n  Head (first 5 rows):")
print(transactions.head())

print("\n  Tail (last 5 rows):")
print(transactions.tail())

print(f"\n  Shape       : {transactions.shape}")
print(f"  Columns     : {list(transactions.columns)}")
print("\n  Data types:")
print(transactions.dtypes)

print("\n  General info:")
transactions.info()

print("\n  ProductCategory and Amount columns:")
print(transactions[['ProductCategory', 'Amount']])

print("\n  Last 3 columns (using iloc):")
print(transactions.iloc[:, -3:])

print("\n  Rows where Region == 'North' and Amount > 200:")
print(transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)])

print("\n  Value counts for ProductCategory:")
print(transactions['ProductCategory'].value_counts())

print("\n  Unique values in Region:")
print(transactions['Region'].unique())

print("\n  Mean Amount grouped by Region:")
print(transactions.groupby('Region')['Amount'].mean())

# ---- C3. Manipulating the DataFrame ----
print("\nC3. Manipulating the DataFrame:")

transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
print("\n  After updating Amount for TransactionID 102 to 165:")
print(transactions)

transactions['Discount'] = transactions['Amount'] * 0.10
print("\n  After adding a 'Discount' column (10% of Amount):")
print(transactions)

transactions = transactions[transactions['TransactionID'] != 109].reset_index(drop=True)
print("\n  After removing the row with TransactionID 109:")
print(transactions)

transactions = transactions.drop(columns=['Discount'])
print("\n  After deleting the 'Discount' column:")
print(transactions)


A1. Week 1 temperatures array:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

A2. Inspection of temperatures_w1:
  Shape       : (7,)
  Data type   : float64
  No. elements: 7

A3. Celsius to Fahrenheit conversion:
  Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
  Max temperature (C): 26.1
  Min temperature (C): 20.8
  Mean temperature (C): 23.5
[22.5 25.3 20.8]

A4. Slicing and Indexing:
  First three days       : [22.5 25.3 20.8]
  Weekend (last 2 days)  : [24.8 21.9]
  Middle three days      : [20.8 23.4 26.1]

A5. 2D temperatures array (rows = weeks):
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

A6. Inspection of 2D temperatures array:
  Shape       : (2, 7)
  Data type   : float64
  No. elements: 14

  Week 1 temperatures       : [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
  Week 2 temperatures       : [19.2 22.5 21.3 24.  23.5 22.8 20.1]
  Week 1 weekend            : [24.8 21.9]
  Week 2 weekend            : [22.8 20.1]
  Both weeks' weekends:
[[24.8 2